--
-- Name: terminal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terminal (
    id bigint NOT NULL,
    verfm character varying(255),
    logic integer NOT NULL,
    model character varying(255),
    mxf integer NOT NULL,
    mxr integer NOT NULL,
    plat integer NOT NULL,
    ptid character varying(255),
    sam integer NOT NULL,
    serial character varying(255),
    version character varying(255)
);


--
-- Name: terminal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terminal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terminal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terminal terminal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminal
    ADD CONSTRAINT terminal_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

